### ISSUE TITLE
Ukol5 mam hotovy

### ISSUE THREAD

**Issue by Julnewst** [Julnewst/python-042023--Ukol5#1]
@pikopira54

Ahoj Petře,

posílám vypracovaný 5. úkol. S posledním zadáním jsem si nebyla jista, co tím chce básník říci,  tak je zpracovaný jak pouze pro jednu vysvětlující proměnnou (o které se hovořilo v zadání) a pak je tam řešení s původními proměnnými + jedna výkonnostní proměnná navíc (jak mi vyplynulo z očekávání v zadání, že model bude přesnější), Snad jsem aspoň něco trefila. :-)

Díky

Julie

**Comment by pikopira54** [comment]
Ahoj, bylo tim mysleno pridat dalsi promennou, kazdopadne i jine holky to resili i s modelem s jednym cvikem, takze obe moznosti jsou OK. Hezky vypracovano.

**Comment by pikopira54** [comment]
+ pochvala za praci navic, v programovani se vzdy hodi prozkoumat vice cest a nechat prip. rozhodnuti na zadavateli

**Comment by Julnewst** [comment]
Děkuji!
